# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Fabio Maria Carlucci
tagline:          'Online CV'
description:      >- I'm a PHDA brazen two-column <a href="https://fmcarlucci.github.io/" >Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.
url:              https://fmcarlucci.github.io/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
  repo:           https://github.com/poole/hyde
