# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Fabio Maria Carlucci
tagline:          'Online CV'
description:      'I am a PhD student at Sapienza University of Rome, advised by <a href="https://scholar.google.com/citations?user=mHbdIAwAAAAJ" target="_blank">Prof. Barbara Caputo</a>. My current research interests are Transfer Learning and Domain Adaptation, in theory and efficient practice.'
url:              https://fmcarlucci.github.io/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
  repo:           https://github.com/poole/hyde
