# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Fabio Maria Carlucci
tagline:          'PhD student in Computer Vision'
description:      'I''m a PhD student at Sapienza University of Rome, advised by <a href="https://scholar.google.com/citations?user=mHbdIAwAAAAJ" target="_blank">Prof. Barbara Caputo</a>. My current research area is Deep Learning applied to machine vision.'
url:              https://fmcarlucci.github.io/
baseurl:          https://fmcarlucci.github.io/

author:
  name:           'Fabio Maria Carlucci'
  #url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
  repo:           https://github.com/fmcarlucci/fmcarlucci.github.io/
